- README.md
- rflx/cli.py
- rflx/parser.py
- tests/test_cli.py
> Optional output directory and handling of absolute file paths

- generated/rflx-builtin_types-conversions.ads
- generated/rflx-builtin_types.ads
- generated/rflx-ipv4-generic_option.adb
- generated/rflx-ipv4-generic_option.ads
- generated/rflx-ipv4-generic_packet.adb
- generated/rflx-ipv4-generic_packet.ads
- generated/rflx-ipv4.ads
- rflx/generator/common.py
- rflx/generator/core.py
- rflx/generator/generator.py
- rflx/generator/parser.py
- rflx/generator/types.py
- rflx/model.py
- rflx/parser.py
- rflx/templates/builtin_types-conversions.ads
- rflx/templates/builtin_types.ads
- specs/ipv4.rflx
- tests/rflx-in_ethernet-tests.adb
- tests/rflx-in_ipv4-tests.adb
- tests/rflx-ipv4-tests.adb
- tests/test_integration.py
> Issue 111: Add built-in Boolean type

- .github/workflows/CI.yml
> Issue 161: Fix caching of Python packages in CI

- rflx/expression.py
- tests/test_expression.py
> Issue 165: Fix incorrect simplification of subtraction

- rflx/parser/grammar.py
- tests/test_parser.py
> Issue 170: Fix parsing of based numeric literal

- rflx/model.py
- tests/test_model.py
> Issue 171: Add check for unreachable fields in model

- .pylintrc
- rflx/cli.py
- rflx/generator/core.py
- rflx/graph.py
- rflx/parser/parser.py
- rflx/pyrflx/pyrflx.py
- tests/__init__.py
- tests/test_cli.py
- tests/test_generator.py
- tests/test_graph.py
> Issue 180: Improve logging

- rflx/model.py
- tests/models.py
- tests/test_model.py
> Issue 187: Fix prefixing of literals when merging messages

- rflx/generator/types.py
- rflx/model.py
- rflx/parser/grammar.py
- rflx/parser/parser.py
- tests/test_parser.py
> Issue 191: Fix arrays of built-in types

- examples/icmp_socket.py
- rflx/ada.py
- rflx/cli.py
- rflx/generator/core.py
- rflx/identifier.py
- tests/test_model.py
- tests/test_pyrflx.py
The new pylint version 2.5.0 detects invalid f-strings now.
> Fix invalid f-strings

- rflx/parser/grammar.py
- tests/test_parser.py
> Issue 221: Fix parsing of mathematical expressions

- rflx/model.py
- tests/test_verification.py
> Prohibit length attribute for Final field

- doc/Limitations.md
- rflx/ada.py
- rflx/expression.py
- rflx/model.py
- tests/test_model.py
- tests/test_parser.py
> Issue 204 and 228: Replacing deprecated decorators and restricting maximum size of scalar types

- rflx/generator/core.py
> Issue 206: Fix failing discriminant check in generated code

- .github/workflows/CI.yml
- Makefile
> Issue 122: Speed up verification jobs in CI

- rflx/expression.py
- rflx/model.py
- rflx/pyrflx/typevalue.py
- tests/test_verification.py
> Issue 235: Statically check aggregate length

- .flake8
- .github/workflows/CI.yml
> Issue 245: Disable flake8 check for ambiguous variable names

- rflx/pyrflx/typevalue.py
- specs/icmp.rflx
- tests/null_message.rflx
- tests/test_integration.py
- tests/test_pyrflx.py
> Issues 220, 174: Fix index error for null messages and add icmp message specifications

- rflx/parser/parser.py
- tests/test_parser.py
> Issue 242: Add check for name conflicts between literals and types

- .github/workflows/CI.yml
- .pylintrc
- Makefile
- bin/rflx
- mypy.ini
- pytest.ini
- requirements.txt
- rflx/ada.py
- rflx/contract.py
- rflx/expression.py
- rflx/identifier.py
- rflx/model.py
- tests/__init__.py
- tests/conftest.py
- tests/message_odd_length.rflx
- tests/test_cli.py
- tests/test_expression.py
- tests/test_generator.py
- tests/test_graph.py
- tests/test_identifier.py
- tests/test_integration.py
- tests/test_model.py
- tests/test_parser.py
- tests/test_pyrflx.py
- tests/test_verification.py
- tests/test_z3.py
- tests/utils.py
> Issue 130, 224: Introduce icontract and pytest

- .github/workflows/tests.yml
> Issue 267: Fix caching in SPARK tests

- rflx/generator/core.py
- tests/test_generator.py
- tests/test_integration.py
> Issue 266: Fix generation of library files

- rflx/model.py
- tests/test_verification.py
> Exclude link condition from link expression

- rflx/pyrflx/typevalue.py
> Issue 254: PyRFLX performance

- generated/rflx-arrays.ads
- generated/rflx-enumeration.ads
- generated/rflx-ethernet.ads
- generated/rflx-ipv4.ads
- generated/rflx-rflx_generic_types.ads
- generated/rflx-tlv.ads
- generated/rflx-udp.ads
- rflx/generator/core.py
- rflx/model.py
- rflx/templates/rflx_generic_types.ads
- test.gpr
- tests/rflx-arrays-tests.adb
- tests/rflx-derivation-tests.adb
- tests/test_model.py
> Issue 258: Enable proof warnings

- tools/generate_spark_test_code.py
This tool allows to regenerate all files in the `generated` directory.
> Add tool for generating SPARK test code

- Makefile
- requirements.txt
- test.gpr
> Use all cores for python and spark tests

- generated/rflx-arrays.ads
- generated/rflx-ethernet.ads
- generated/rflx-ipv4.ads
- generated/rflx-tlv.ads
- generated/rflx-udp.ads
- rflx/ada.py
- rflx/generator/core.py
- rflx/model.py
- setup.py
- test.gpr
- tests/test_model.py
Close #312 
Close #313 
Close #314  
Close #315 
Close #316
> Issue 312, 313, 314, 315, 316: Prevent compilation errors in generated code

- rflx/error.py
- rflx/generator/common.py
- rflx/model.py
- rflx/parser/ast.py
- rflx/parser/grammar.py
- rflx/parser/parser.py
- tests/test_model.py
- tests/test_parser.py
Close #309
Close #310
Close #311
Close #319
> Issue 309, 310, 311, 319: Add checks to model

- test.gpr
> Issue 324: Silence "no suffices" warning in test.gpr

- rflx/model.py
- specs/tls_handshake.rflx
- tests/enumeration_type.rflx
- tests/feature_integration.rflx
- tests/message_in_message.rflx
- tests/test_integration.py
- tests/test_model.py
- tests/test_parser.py
- tests/test_verification.py
> Issue 288: Missing check of size and alignment of opaque fields

- rflx/model.py
- rflx/parser/grammar.py
- tests/test_parser.py
> Issue 338: New-line and missing location in conflict info

- generated/rflx-arrays-av_enumeration_vector.ads
- generated/rflx-arrays-enumeration_vector.ads
- generated/rflx-arrays-inner_messages.ads
- generated/rflx-arrays-modular_vector.ads
- generated/rflx-arrays-range_vector.ads
- generated/rflx-ipv4-options.ads
- rflx/generator/core.py
- tests/test_integration.py
> Issue 349: Fix code generation for array with imported element type

- rflx/model.py
- rflx/pyrflx/typevalue.py
- tests/test_verification.py
> Issue 351: Fix handling of prefixed literals in model verification

- .github/workflows/tests.yml
> Issue 332: Show proof statistics and speed up verification in CI

- .coveragerc
- .github/workflows/tests.yml
- .pylintrc
- Makefile
- README.md
- mypy.ini
- rflx/ada.py
- rflx/error.py
- rflx/expression.py
- rflx/generator/common.py
- rflx/generator/core.py
- rflx/model.py
- rflx/pyrflx/typevalue.py
- setup.py
- tools/check_dependencies.py
Closes #59 
Closes #357 
Closes #364
> Issue 59, 357, 364: Python 3.7, mypy options and dependency check

- tests/property/strategies.py
> Issue 372: Enable debugging of incorrectly generated messages

- rflx/model.py
- tests/test_model.py
> Issue 375: Fix incorrect detection of possibly empty array fields

- tests/property/strategies.py
This should fix a occasionally occurring error in mypy.
> Replace remaining named tuple by data class

- README.md
- doc/Language-Reference.md
- examples/ping/specs/icmp.rflx
- examples/ping/specs/ipv4_option.rflx
- rflx/model.py
- rflx/parser/grammar.py
- specs/ethernet.rflx
- specs/icmp.rflx
- specs/ipv4.rflx
- specs/tls_handshake.rflx
- specs/tls_record.rflx
- specs/tlv.rflx
- tests/message_type.rflx
- tests/test_integration.py
- tests/tlv_with_checksum.rflx
> Issue 380: Change message syntax

- rflx/model.py
- tests/test_verification.py
> Issue 389: Fix premature verification of unproven messages

- setup.py
> Issue 393: Enable type checking for users of rflx package

- rflx/pyrflx/pyrflx.py
- rflx/pyrflx/typevalue.py
- tests/test_pyrflx.py
> Issues 406, 407: Iterator over packages and fix assertion

- test.gpr
> Issue 414: Enable displaying message graphs in test project

- .isort.cfg
- Makefile
- ide/gnatstudio/recordflux.py
- rflx/ada.py
- rflx/generator/core.py
- rflx/parser/grammar.py
- rflx/pyrflx/typevalue.py
- setup.py
- tests/property/strategies.py
- tests/property/test_parser.py
> Issue 331: Upgrade to isort 5 and pylint 2.6.0

- Makefile
- doc/Language-Reference.md
- rflx/ada.py
- rflx/cli.py
- rflx/common.py
- rflx/declaration.py
- rflx/error.py
- rflx/expression.py
- rflx/generator/common.py
- rflx/model.py
- rflx/parser/ast.py
- rflx/parser/grammar.py
- rflx/parser/parser.py
- rflx/pyrflx/package.py
- rflx/pyrflx/typevalue.py
- rflx/session.py
- rflx/sessionfile.py
- rflx/statement.py
- tests/property/strategies.py
- tests/property/test_parser.py
- tests/test_expression.py
- tests/test_graph.py
- tests/test_integration.py
- tests/test_model.py
- tests/test_parser.py
- tests/test_session_validate.py
- tests/test_sessionfile.py
- tests/tls_handshake_session.rflx
- tests/tls_record_session.rflx
- tests/utils.py
> Issue 291: Add support for session specifications

- rflx/expression.py
- tests/test_z3.py
Attribute was not properly negated in `z3expr`.
> Fix negation bug for z3expr of Attribute

- Makefile
- examples/ping/ping.py
- rflx/ada.py
- rflx/expression.py
- rflx/generator/common.py
- rflx/generator/core.py
- rflx/generator/generator.py
- rflx/generator/parser.py
- rflx/model/message.py
- rflx/model/model.py
- rflx/model/session.py
- rflx/model/type_.py
- rflx/parser/grammar.py
- rflx/parser/parser.py
- rflx/pyrflx/typevalue.py
- setup.py
- tests/property/strategies.py
- tests/test_expression.py
- tests/test_model.py
- tests/test_model_session.py
- tests/test_parser.py
- tests/test_pyrflx.py
- tests/test_session_validate.py
- tests/test_verification.py
- tests/test_z3.py
> Issue 427: Upgrade to black 20.8b

- rflx/pyrflx/typevalue.py
- tests/test_pyrflx.py
> Issue 423: Raise exception when generating bytestring from invalid message

- .pylintrc
- rflx/expression.py
- rflx/model/message.py
- rflx/model/type_.py
- rflx/typing_.py
- tests/unit/expression_test.py
- tests/unit/model/message_test.py
- tests/unit/model/model_test.py
- tests/unit/typing_test.py
> Issue 87: Type-check expressions

- rflx/cli.py
- rflx/parser/cache.py
- rflx/parser/parser.py
- tests/models.py
- tests/unit/parser/cache_test.py
- tests/unit/parser/parser_test.py
> Issue 442: Add caching of message verification results to parser

- rflx/model/session.py
- rflx/parser/grammar.py
- tests/integration/session/tls_handshake_session.rflx
- tests/integration/session/tls_record_session.rflx
- tests/unit/model/session_test.py
> Issue 453: Add description aspects to session specification

- .github/workflows/tests.yml
> Issue 454: Replace deprecated commands in tests workflow

- tests/unit/model/message_test.py
> Issue 413: Add test for detection of references to optional fields

- rflx/parser/cache.py
- tests/test_cli.py
> Issue 459: Prevent race condition in creation of cache directory

- doc/Language-Reference.md
- examples/specs/ipv4.rflx
- examples/specs/tls_handshake.rflx
- examples/specs/tls_heartbeat.rflx
- examples/specs/udp.rflx
- rflx/model/message.py
- rflx/specification/ast.py
- rflx/specification/grammar.py
- rflx/specification/parser.py
- tests/ide/ide_test.py
- tests/integration/specification_model_test.py
- tests/unit/specification/parser_test.py
- tools/check_doc.py
> Issue 95, 343: Allow field condition and aspects without then clause

- README.md
- examples/apps/icmp_socket.py
- examples/apps/ping/ping.py
- rflx/pyrflx/pyrflx.py
- tests/data/fixtures/pyrflx.py
- tests/integration/benchmark.py
- tests/integration/pyrflx_test.py
- tests/unit/pyrflx_test.py
> Allow PyRFLX object creation directly from model

- rflx/cli.py
- rflx/pyrflx/pyrflx.py
- rflx/specification/grammar.py
- rflx/specification/parser.py
- tests/data/specs/context.rflx
- tests/ide/ide_test.py
- tests/unit/specification/parser_test.py
> Issue 447, 448: Improve specification parser

- rflx/cli.py
- rflx/generator/generator.py
- rflx/model/model.py
- tests/integration/specs_test.py
- tests/unit/generator_test.py
- tests/utils.py
- tools/generate_spark_test_code.py
> Issue 470: Change generator interface

- rflx/model/message.py
- rflx/model/model.py
- rflx/specification/parser.py
- tests/data/models.py
- tests/data/specs/duplicate_type.rflx
- tests/ide/ide_test.py
- tests/integration/specification_model_test.py
- tests/unit/model/message_test.py
- tests/unit/model/model_test.py
- tests/unit/specification/parser_test.py
> Issue 456: Move checks from parser into model

- rflx/ada.py
- rflx/common.py
- rflx/declaration.py
- rflx/expression.py
- rflx/generator/common.py
- rflx/generator/generator.py
- rflx/generator/parser.py
- rflx/generator/serializer.py
- rflx/graph.py
- rflx/model/__init__.py
- rflx/model/session.py
- rflx/model/type_.py
- rflx/specification/ast.py
- rflx/specification/grammar.py
- rflx/specification/parser.py
- tests/data/models.py
- tests/unit/generator_test.py
- tests/unit/graph_test.py
- tests/unit/model/session_test.py
> Issue 463: Use consistent naming for identifiers

- rflx/model/message.py
- rflx/model/session.py
- rflx/model/type_.py
- tests/integration/specification_model_generator_test.py
- tests/unit/model/message_test.py
- tests/unit/model/type_test.py
> Issue 384: Allow using size of static types in expressions and refactor message model

- rflx/specification/grammar.py
- tests/unit/specification/grammar_test.py
> Issue 476: Add modulo operation to specification parser

- rflx/expression.py
- rflx/model/message.py
- tests/unit/expression_test.py
- tests/unit/model/message_test.py
> Issue 492: Enable specification of discontiguous optional fields

- .github/workflows/tests.yml
> Issue 512: Fix installation check in CI

- tests/spark/rflx-ipv4_tests.adb
> Issue 516: Suppress false positive about unreachable code

- rflx/statement.py
- tests/integration/session/tls_handshake_session.rflx
- tests/unit/model/session_test.py
> Issue 514: Prohibit appending independently created message

- rflx/identifier.py
- rflx/model/model.py
- tests/ide/ide_test.py
- tests/integration/session/greentls.rflx
- tests/integration/session/tls_handshake_session.rflx
- tests/integration/session/tls_record_session.rflx
- tests/unit/identifier_test.py
- tests/unit/model/model_test.py
> Issue 520: Fix detection of name conflicts between enum literals and types

- rflx/model/message.py
- tests/unit/model/message_test.py
> Issue 522: Fix type checking of messages

- rflx/generator/generator.py
- tests/integration/specification_model_generator_test.py
> Use ordered dict for arrays in default instances

- rflx/pyrflx/typevalue.py
- tests/unit/pyrflx_test.py
> Issue 533: Fix handling of empty opaque fields

- Makefile
- rflx/generator/generator.py
- rflx/model/message.py
- tests/integration/specification_model_generator_test.py
- tests/spark/generated/rflx-in_ipv4-generic_contains.ads
- tests/unit/model/message_test.py
> Issue 530: Fix handling of enum literals in refinement conditions

- .github/workflows/tests.yml
- Makefile
- tools/check_packages.py
> Issue 552: Fix checking of test modules

- rflx/pyrflx/typevalue.py
- tests/data/fixtures/pyrflx.py
- tests/data/specs/message_size.rflx
- tests/unit/pyrflx_test.py
> Issue 525: Messages cannot be parsed if Specification contains condition with Message'Size

- rflx/specification/cache.py
- tests/unit/specification/cache_test.py
> Issue 584: Consider changes to field types in verification cache

- README.md
- doc/Language-Reference.md
- rflx/model/message.py
- rflx/pyrflx/typevalue.py
- tests/data/models.py
- tests/data/specs/tlv.rflx
- tests/data/specs/tlv_with_checksum.rflx
- tests/ide/ide_test.py
- tests/integration/session/greentls.rflx
- tests/integration/specs_test.py
- tests/property/strategies.py
- tests/spark/generated/rflx-enumeration.ads
- tests/spark/generated/rflx-tlv.ads
- tests/spark/rflx-derivation_tests.adb
- tests/spark/rflx-enumeration_tests.adb
- tests/spark/rflx-in_tlv_tests.adb
- tests/spark/rflx-tlv_tests.adb
- tests/unit/pyrflx_test.py
> Issue 579: Ensure message size is multiple of 8 bit

- rflx/generator/generator.py
- tests/integration/specification_model_generator_test.py
- tests/spark/generated/rflx-in_ethernet-generic_contains.adb
- tests/spark/generated/rflx-in_ethernet-generic_contains.ads
- tests/spark/generated/rflx-in_ipv4-generic_contains.adb
- tests/spark/generated/rflx-in_ipv4-generic_contains.ads
> Issue 593: Make refinement context parameters unique in Switch_To_*

- rflx/model/session.py
- rflx/specification/parser.py
- setup.py
- tests/integration/session/tls_handshake_session.rflx
- tests/integration/session/tls_record_session.rflx
- tests/unit/model/session_test.py
- tests/unit/specification/grammar_test.py
> Issue 544: Add exception transition to session states

- rflx/specification/cache.py
- rflx/specification/parser.py
- tests/unit/specification/cache_test.py
Closes #604
Closes #543
Closes #511
> Issue 511, 543, 604: Fix bugs related to verification cache

- rflx/pyrflx/typevalue.py
- tests/unit/pyrflx_test.py
This fixes a bug that prevented the parsing of a field of type `Array` if the size of the field depends upon `Message'Last`.·
See https://github.com/Componolit/RecordFlux/issues/606#issuecomment-802177330.·
However, it is not possible to parse a DHCP message (or more specifically an `Option` message) because of #559.
Closes #606
> Issue 606: Fix parsing of Array fields with size depending on Message'Last

- rflx/pyrflx/typevalue.py
- tests/data/fixtures/pyrflx.py
- tests/data/specs/message_type_size_condition.rflx
- tests/unit/pyrflx_test.py
This fixes a bug where an exception was thrown while parsing a message if the associated spec references a type's size in a condition.
Closes #559
> Issue 559: Fix parsing of messages using type size in condition

- README.md
- doc/Development.md
- rflx/declaration.py
- rflx/model/session.py
- rflx/typing_.py
> Issue 597: Update dependencies in README, improve development documentation and fix pylint errors

- rflx/pyrflx/typevalue.py
- tests/unit/pyrflx_test.py
This PR adds a set_fields property to the MessageValue class. 
Closes #615
> Issue 615: Add set_fields property to MessageValue

- .github/workflows/tests.yml
- Makefile
This will split the tests workflow into multiple separate workflows. Each workflow is only triggered by changes to files in specified directories to prevent the execution of tests for unchanged code. All tests will still be performed on a daily basis (nightly tests).
> Improve runtime of CI workflow

- README.md
- rflx/cli.py
- setup.py
> Issue 603: Update parser to 0.2.1, display parser version

- Makefile
- mypy.ini
- rflx/cli.py
- tests/unit/cli_test.py
> Issue 655: Add version and optimization information to bug box

- mypy.ini
- setup.py
> Issue 416: Upgrade to pytest 6

- rflx/specification/parser.py
- tests/unit/specification/parser_test.py
> Issue 666: Fix incorrectly formatted location in error messages

- setup.py
- tests/unit/specification/parser_test.py
Closes #600
Closes #678
Use parser version 0.5.1 which enables the use of keywords as identifiers.
> Issue 600, 678: Support keywords as identifiers

- .github/ISSUE_TEMPLATE/vulnerability.md
- SECURITY.md
> Add security policy and corresponding issue template

- rflx/pyrflx/package.py
- rflx/pyrflx/pyrflx.py
- tests/unit/pyrflx_test.py
Set checksum functions for all messages in every package in a PyRFLX object.
> Issue 697: Set checksum functions on PyRFLX level

- doc/Language-Reference.md
- rflx/specification/parser.py
- tests/data/specs/ipv4.rflx
- tests/unit/specification/parser_test.py
> Issue 617: Change semantics of field conditions

- Makefile
- doc/Development.md
- doc/Language-Reference.adoc
- examples/apps/dhcp_client/specs/dhcp_client.rflx
- setup.py
- tests/unit/specification/grammar_test.py
- tools/upgrade_dependencies.py
- Closes #702
Also, a small tool for upgrading all development dependencies is added.
> Issue 702: Change syntax of list comprehensions

- rflx/pyrflx/pyrflx.py
- tests/unit/pyrflx_test.py
See https://github.com/Componolit/RecordFlux-specifications/pull/69#discussion_r683312950
> Don't raise error when setting checksum for unknown package

- doc/Language-Reference.adoc
- tools/check_requirements.py
> Issue 715: Move requirements tags into comments

- rflx/generator/generator.py
- tests/integration/specification_model_generator_test.py
- tests/spark/generated/rflx-sequence-inner_message.adb
- tests/spark/generated/rflx-udp-datagram.adb
> Issue 726: Fix code generation for expressions with values outside type range

- rflx/model/message.py
- tests/unit/model/message_test.py
> Issue 729: Replace message attributes when merging message types

- ide/gnatstudio/recordflux.py
- rflx/cli.py
- rflx/specification/parser.py
> Add --no-verification flag for all subcommands

- rflx/cli.py
- rflx/expression.py
- rflx/model/message.py
- rflx/specification/parser.py
- tests/unit/specification/parser_test.py
> Issue 755: Make number of workers for message verification configurable

- rflx/generator/session.py
- rflx/model/message.py
- tests/integration/specification_model_generator_test.py
- tests/unit/generator_test.py
> Issue 770, 771: Fix code generation

- rflx/expression.py
- rflx/generator/common.py
- rflx/model/declaration.py
- rflx/model/message.py
- rflx/model/session.py
- rflx/pyrflx/typevalue.py
- tests/integration/specification_model_test.py
- tests/unit/expression_test.py
- tests/unit/generator_test.py
- tests/unit/graph_test.py
- tests/unit/model/session_test.py
> Issue 780: Ensure consistency between parsing and generation of specifications

- README.md
- rflx/pyrflx/package.py
- rflx/pyrflx/pyrflx.py
- rflx/pyrflx/typevalue.py
- tests/data/fixtures/pyrflx.py
- tests/data/specs/parameterized.rflx
- tests/unit/pyrflx_test.py
> Issue 743: Support parameterized messages in PyRFLX

- examples/apps/ping/ping.py
- rflx/pyrflx/package.py
- rflx/pyrflx/pyrflx.py
- tests/integration/benchmark.py
- tests/integration/pyrflx_test.py
> Remove __getitem__ from PyRFLX

- .github/workflows/tests.yml
- Makefile
- README.md
- doc/Development.md
- test.gpr
- tests/utils.py
> Issue 674: Ensure compatibility to FSF GNAT 11

- doc/Development.md
- setup.py
> Issue 745: Fix PyPI installation

- doc/Design-Guide.md
- doc/Development.md
- tests/README.md
> Issue 849: Improve documentation of development process

- rflx/model/session.py
- tests/integration/specification_model_test.py
- tests/unit/model/session_test.py
> Issue 854: Add error for declarations in IO states

- rflx/pyrflx/typevalue.py
- tests/data/specs/parameterized.rflx
- tests/data/validator/parameterized/message/invalid/parameterized_message_excess_parameter.yaml
- tests/data/validator/parameterized/message/invalid/parameterized_message_missing_parameter.yaml
- tests/data/validator/parameterized/message/valid/parameterized_message.yaml
- tests/unit/pyrflx_test.py
- tests/unit/validator_test.py
> Issue 865: Fix validator crash for parameters with enumeration type

- rflx/pyrflx/typevalue.py
- rflx/validator.py
- tests/integration/pyrflx_test.py
- tests/unit/pyrflx_test.py
> Recursively convert Typevalue to JSON

- rflx/model/message.py
- tests/unit/model/message_test.py
> Substitute parameters in inner links when merging messages

- rflx/generator/session.py
- tests/integration/session_functions/config.yml
- tests/integration/session_functions/generated/rflx-test-session.adb
- tests/integration/session_functions/generated/rflx-test-session.ads
- tests/integration/session_functions/src/func.adb
- tests/integration/session_functions/src/func.ads
- tests/integration/session_functions/test.rflx
- tests/unit/ada_test.py
- tests/unit/generator_test.py
> Handle Boolean builtin type in formal function types

- rflx/generator/allocator.py
- rflx/generator/session.py
- tests/unit/generator_test.py
- Fix noncompilable code for session without allocation points
- Fix noncompilable code for session without IO states
Fixes #883
Fixes #884
> Issue 883 and 884: Fix code generation for trivial sessions

- rflx/cli.py
- rflx/identifier.py
- rflx/pyrflx/pyrflx.py
- rflx/specification/parser.py
- tests/integration/parameterized_messages/generated/rflx-test-session.ads
- tests/integration/session_functions/generated/rflx-test-session.adb
- tests/integration/session_functions/generated/rflx-test-session.ads
- tests/integration/session_functions/generated/rflx-test.ads
- tests/integration/session_functions/src/func.adb
- tests/integration/session_functions/src/func.ads
- tests/integration/session_functions/test.rflx
- tests/integration/specification_model_test.py
- tests/unit/expression_test.py
- tests/unit/generator_test.py
- tests/unit/identifier_test.py
- tests/unit/specification/grammar_test.py
> Issue 892: Fix type qualification

- rflx/templates/rflx_generic_types.ads
- tests/integration/specification_model_generator_test.py
- tests/utils.py
> Issue 897: Fix prefix in generated code and related test utils

- .github/workflows/tests.yml
Fixes use of undeclared variable `matrix.python-version`.
> Fix used Python versions in tests workflow

- rflx/pyrflx/typevalue.py
- tests/data/fixtures/pyrflx.py
- tests/data/specs/low_order.rflx
- tests/data/specs/nested_byte_order.rflx
- tests/unit/pyrflx_test.py
> Issue 913: Validation fails for boolean fields in inner messages with Low_Order_First

- .github/workflows/tests.yml
- Makefile
- defaults.gpr
- examples/apps/dhcp_client/Makefile
- examples/apps/ping/Makefile
- tests/spark/Makefile
- tests/utils.py
This change allows the memcached to be set via a make variable or via an environment variable. If nothing is set the defaults will be kept.
> Make memcached configurable

- defaults.gpr
> Issue 951: Fix proof regression on `main`

- rflx/generator/session.py
- tests/integration/session_variable_initialization/generated/rflx-test-session.adb
- tests/integration/session_variable_initialization/generated/rflx-test-session.ads
- tests/integration/session_variable_initialization/test.rflx
> Issue 954: Ensure initialization of all session context components

- README.md
> Issue 879: Fix incorrect examples in README

- rflx/expression.py
- rflx/pyrflx/typevalue.py
- tests/data/fixtures/pyrflx.py
- tests/data/specs/aggregate_in_relation.rflx
- tests/unit/expression_test.py
- tests/unit/pyrflx_test.py
> Add support for relations with aggregates and variables in pyrflx

- rflx/specification/cache.py
- tests/unit/specification/cache_test.py
> Issue 1028: Keep multiple message versions in verification cache

- rflx/model/message.py
- tests/integration/specification_model_test.py
> Issue 1033: Prevent assertion error on messages with unreachable fields

- rflx/pyrflx/typevalue.py
> Fix undefined attribute

- rflx/expression.py
- rflx/generator/session.py
- tests/integration/specification_model_generator_test.py
> Issue 1059: Fix code generation for boolean relations with global variables

- rflx/error.py
- rflx/expression.py
- rflx/generator/generator.py
- rflx/graph.py
- rflx/identifier.py
- rflx/model/declaration.py
- rflx/model/message.py
- rflx/model/model.py
- rflx/model/session.py
- rflx/model/type_.py
- rflx/pyrflx/package.py
- rflx/pyrflx/pyrflx.py
- rflx/pyrflx/typevalue.py
- rflx/specification/parser.py
- rflx/validator.py
- tests/unit/model/message_test.py
> Issue 784: Make naming of private class attributes consistent

- .github/workflows/tests.yml
- Makefile
> Issue 1065: Fix alr options

- .github/workflows/changelog.yml
- CHANGELOG.md
"Unreleased" should reflect all changes till today. Several tickets are not referenced, as they refer to issues in features which were not present in previous versions. For previous releases, I just added the existing changelogs.
Closes #1047
> Issue 1047: Add changelog

- CHANGELOG.md
- rflx/model/statement.py
- tests/integration/parameterized_messages/config.yml
- tests/integration/parameterized_messages/generated/rflx-test-session.adb
- tests/integration/parameterized_messages/generated/rflx-test-session.ads
- tests/integration/parameterized_messages/test.rflx
> Issue 1080: Fix missing type information in Reset statement

- .github/workflows/tests.yml
> Enable parallelism on dhcp_client test

- examples/apps/dhcp_client/Makefile
- rflx/ada.py
- rflx/generator/session.py
- rflx/model/message.py
- tests/integration/messages_with_implict_size/generated/rflx-test-session.adb
- tests/integration/messages_with_single_opaque_field/generated/rflx-test-session.adb
- tests/integration/parameterized_messages/generated/rflx-test-session.adb
- tests/integration/session_append_unconstrained/generated/rflx-test-session.adb
- tests/integration/session_binding/generated/rflx-test-session.adb
- tests/integration/session_case_expression_aggregate/generated/rflx-test-session.adb
- tests/integration/session_case_expression_numeric/generated/rflx-test-session.adb
- tests/integration/session_comprehension_on_message_field/generated/rflx-test-session.adb
- tests/integration/session_comprehension_on_sequence/generated/rflx-test-session.adb
- tests/integration/session_endianness/generated/rflx-test-session.adb
- tests/integration/session_functions_opaque/generated/rflx-test-session.adb
- tests/integration/session_integration/generated/rflx-test-session.adb
- tests/integration/session_sequence_append/generated/rflx-test-session.adb
- tests/integration/session_sequence_append_head/generated/rflx-test-session.adb
- tests/integration/session_setting_of_message_fields/generated/rflx-test-session.adb
- tests/integration/session_simple/generated/rflx-test-session.adb
- tests/integration/session_variable_initialization/generated/rflx-test-session.adb
- tests/unit/generator_test.py
- tests/unit/model/message_test.py
> Issue 908: Improve binary size (part 7)

- .github/workflows/edge_tests.yml
- .github/workflows/tests.yml
- CHANGELOG.md
- examples/apps/dhcp_client/Makefile
- rflx/generator/message.py
- tests/integration/messages_with_single_opaque_field/generated/rflx-test-message.ads
- tests/integration/parameterized_messages/generated/rflx-test-message.ads
- tests/integration/session_case_expression_numeric/generated/rflx-test-message.ads
- tests/integration/session_endianness/generated/rflx-messages-msg.ads
- tests/integration/session_endianness/generated/rflx-messages-msg_le.ads
- tests/integration/session_endianness/generated/rflx-messages-msg_le_nested.ads
- tests/integration/session_functions/generated/rflx-test-definite_message.ads
- tests/integration/session_sequence_append_head/generated/rflx-tlv-message.ads
- tests/integration/shared/generated/rflx-universal-message.ads
- tests/integration/shared/generated/rflx-universal-option.ads
- tests/spark/generated/rflx-derivation-message.ads
- tests/spark/generated/rflx-enumeration-message.ads
- tests/spark/generated/rflx-ethernet-frame.ads
- tests/spark/generated/rflx-expression-message.ads
- tests/spark/generated/rflx-fixed_size-simple_message.ads
- tests/spark/generated/rflx-icmp-message.ads
- tests/spark/generated/rflx-ipv4-option.ads
- tests/spark/generated/rflx-ipv4-packet.ads
- tests/spark/generated/rflx-sequence-inner_message.ads
- tests/spark/generated/rflx-sequence-message.ads
- tests/spark/generated/rflx-sequence-messages_message.ads
- tests/spark/generated/rflx-sequence-sequence_size_defined_by_message_size.ads
- tests/spark/generated/rflx-tlv-message.ads
- tests/spark/generated/rflx-udp-datagram.ads
> Support newer GNAT versions

- .github/workflows/tests.yml
- CHANGELOG.md
- Makefile
- defaults.gpr
> Issue 1124: Fix use of unintended FSF GNAT version in CI

- Makefile
- doc/language_reference/index.rst
- doc/user_guide/index.rst
- rflx/specification/parser.py
- rflx/specification/style.py
- tests/README.md
- tests/data/no_code_blocks_1.rst
- tests/data/no_code_blocks_2.rst
- tests/data/with_code_blocks.rst
- tests/integration/specification_model_generator_test.py
- tests/integration/specification_model_test.py
- tests/tools/check_doc_test.py
- tests/unit/specification/grammar_test.py
- tests/unit/specification/parser_test.py
- tools/check_doc.py
Closes #880 
- Adapt to reStructured Text
- Fix broken checking
- Add unit tests for `doc_check.py`
- Fix documentation
> Issue 880: Fix documentation code block checking

- Makefile
- setup.py
> Issue 1135: Add timeout of one hour for each Python test case

- tests/integration/feature_test.py
- tests/integration/session_sequence_append_head/config.yml
> Issue 1137: Add checking of config file format for feature tests

- rflx/generator/allocator.py
- rflx/generator/session.py
- tests/integration/session_comprehension_on_sequence/generated/rflx-test-session.adb
- tests/integration/session_comprehension_on_sequence/generated/rflx-test-session_allocator.ads
- tests/integration/session_sequence_append_head/config.yml
- tests/integration/session_sequence_append_head/generated/rflx-test-session.adb
- tests/integration/session_sequence_append_head/generated/rflx-test-session.ads
- tests/integration/session_sequence_append_head/generated/rflx-test-session_allocator.adb
- tests/integration/session_sequence_append_head/generated/rflx-test-session_allocator.ads
- tests/integration/session_sequence_append_head/test.rfi
- tests/integration/session_sequence_append_head/test.rflx
> Issue 1132: Fix invalid handling of buffers of sequence copies

- Makefile
We achieve a whopping 3.5% documentation coverage :stuck_out_tongue_winking_eye:  The minimum coverage should be increased from time to time until we achieve 100%.
Closes #1088
Closes #1109
> Issue 1088: Check documentation coverage using interrogate

- .github/workflows/edge_tests.yml
- .github/workflows/tests.yml
- CHANGELOG.md
- README.md
- rflx/contract.py
- setup.py
- tests/integration/feature_test.py
Closes #1142 
With Python 3.10 a branch dependent on `__debug__` is considered uncovered:
```
Name               Stmts   Miss Branch BrPart  Cover   Missing
--------------------------------------------------------------
rflx/contract.py       2      0      2      1    75%   1->exit
--------------------------------------------------------------
TOTAL               9770      0   4371      1    99%
```
I don't see another solution than to exclude this branch from the coverage analysis.
> Issue 1142: Remove support for Python 3.7 and add support for Python 3.10

- CHANGELOG.md
- rflx/specification/parser.py
- tests/ide/ide_test.py
- tests/unit/specification/grammar_test.py
- tests/unit/specification/parser_test.py
- tests/utils.py
> Issue 714: Check for duplicate aspects

- .github/workflows/edge_tests.yml
- .github/workflows/tests.yml
- Makefile
> Issue 1135: Add timeout for calculation of test coverage and re-schedule nightly tests

- README.md
> Issue 1160: Add protocol session to project description

- .github/workflows/pages.yml
- doc/conf.py
> Issue 1002: Deploy documentation to GitHub pages

- .github/workflows/tests.yml
- Makefile
- defaults.gpr
- examples/apps/dhcp_client/dhcp_client.gpr
- rflx/common.py
- tests/spark/test.gpr
- tests/unit/ada_test.py
- tests/unit/expression_test.py
- tests/unit/model/message_test.py
- tests/unit/model/session_test.py
- tests/utils.py
> Issue 1011, 1127: Refactoring and removing of testing with Ada runtime

- CHANGELOG.md
- MANIFEST.in
- Makefile
- README.md
- SECURITY.md
- doc/development_guide/index.rst
- doc/index.rst
- doc/user_guide/index.rst
- setup.py
> Issue 1158: Release 0.6.0

- CHANGELOG.md
> Issue 1158: Improve changelog

- Makefile
- tests/spark/Makefile
> Remove interrogate tool and CVC4-only proofs

- CHANGELOG.md
- doc/development_guide/index.rst
- rflx/cli.py
- setup.py
- tests/unit/cli_test.py
> Issue 795: Add subcommand to install GNAT Studio plugin

- .github/workflows/fixup.yml
> Issue #1167: Check for FIXUP commits

- CHANGELOG.md
- ide/gnatstudio/recordflux.py
- rflx/cli.py
- tests/unit/cli_test.py
> Issue 987: Require --unsafe option with --no-verification

- CHANGELOG.md
- doc/language_reference/index.rst
- rflx/model/__init__.py
- rflx/model/type_.py
- rflx/specification/const.py
- rflx/specification/parser.py
- rflx/typing_.py
- setup.py
- tests/integration/specification_model_test.py
- tests/unit/generator_test.py
- tests/unit/model/session_test.py
- tests/unit/specification/grammar_test.py
- tests/unit/typing_test.py
> Issue 1156: Remove private type support

- .github/workflows/tests.yml
- .gitignore
- .vscode/settings.json
- .vscode/tasks.json
- Makefile
- doc/development_guide/index.rst
- rflx/cli.py
- tests/unit/ada_test.py
- tests/unit/cli_test.py
- tests/unit/generator_test.py
- tests/unit/specification/parser_test.py
- Add test coverage support for vscode
- Disable tests that require compilation in unit tests (hard to support in vscode)
- Improve test coverage of the remaining tests to reach 100% coverage again
> @senier vscode coverage

- CHANGELOG.md
- rflx/graph.py
- rflx/model/message.py
- rflx/model/type_.py
- rflx/pyrflx/typevalue.py
> Issue 643: Change representation of null messages

- CHANGELOG.md
- rflx/generator/generator.py
- tests/unit/cli_test.py
- tests/unit/generator_test.py
> Fail if a generated file exists already

- CHANGELOG.md
- rflx/cli.py
- rflx/common.py
- rflx/converter/iana.py
- rflx/error.py
- rflx/specification/parser.py
- tests/data/bootp-dhcp-parameters.xml
- tests/tools/check_doc_test.py
- tests/unit/cli_test.py
- tests/unit/converter_test.py
- tests/unit/specification/grammar_test.py
- tests/utils.py
- tools/check_doc.py
> Issue 708: Integrate IANA tool

- CHANGELOG.md
- Makefile
- rflx/specification/parser.py
- tests/ide/ide_test.py
- tests/unit/specification/parser_test.py
> Issue 759: Improve handling of specification dependencies

- CHANGELOG.md
> Issue 1210: Update submodules and add 0.7.0 to CHANGELOG

- .vscode/tasks.json
- rflx/specification/parser.py
- tests/unit/specification/grammar_test.py
- tests/unit/specification/parser_test.py
> Check for boolean expressions in math context (and vice versa)

- rflx/generator/common.py
Please let me know if you think this documentation describes the context predicate clearly and sufficiently.
> Add documentation for context predicate

- CHANGELOG.md
> Issue 1243: Add 0.7.1 to CHANGELOG

- rflx/generator/session.py
- rflx/model/declaration.py
- rflx/model/session.py
- tests/unit/generator_test.py
- tests/unit/model/session_test.py
> Issue 1186: Remove unused code for type declarations in sessions

- CHANGELOG.md
- rflx/error.py
- rflx/expression.py
- rflx/model/message.py
- rflx/model/type_.py
- rflx/specification/parser.py
- tests/data/models.py
- tests/data/specs/tlv_with_checksum.rflx
- tests/integration/specification_model_generator_test.py
- tests/spark/generated/rflx-fixed_size-simple_message.adb
- tests/spark/generated/rflx-fixed_size-simple_message.ads
- tests/unit/model/message_test.py
> Issue 662: Detection of always True conditions

- CHANGELOG.md
- doc/language_reference/index.rst
> Make type declaration / sequence type part of basic declaration

- CHANGELOG.md
> Add 0.8.0 to CHANGELOG
