Componolit/RecordFlux

rflx/cli.py
Set the (undocumented) RFLX_REPRODUCIBLE environment variable to enable reproducible code generation. (I got tired of rebasing this change over and over again ;)
=> Allow reproducible generation through env variable

.github/workflows/CI.yml, Makefile, rflx/ada.py, rflx/expression.py, rflx/identifier.py, rflx/model.py
- Optimizing the hash functions led to a 25 % lower runtime for generating code for a specification.
- Running unit tests without calculation of code coverage leads to a significant lower runtime.
=> Improve performance

requirements.txt
Because of a bug in icontract 2.3.3 our automated tests failed last night. This issue is fixed in version 2.3.4, which also provides a significant performance improvement.
=> Increase minimum required version of icontract

examples/icmp_socket.py, rflx/pyrflx/typevalue.py, specs/icmp.rflx, tests/test_pyrflx.py
=> Issue 174, 289: Update ICMP Specification

README.md, generated/rflx-arrays-generic_inner_message.ads, generated/rflx-ethernet-generic_frame.ads, generated/rflx-expression-generic_message.ads, generated/rflx-ipv4-generic_option.ads, generated/rflx-ipv4-generic_packet.ads, generated/rflx-tlv-generic_message.ads, generated/rflx-udp-generic_datagram.ads, rflx/generator/generator.py, test.gpr, tests/rflx-arrays-tests.adb, tests/rflx-ethernet-tests.adb, tests/rflx-in_ethernet-tests.adb, tests/rflx-in_ipv4-tests.adb, tests/rflx-ipv4-tests.adb, tests/rflx-tlv-tests.adb
- Allow proving length properties in composite setters
=> Issue 287: Fix missing SPARK_Mode in generic Write procedures in tests

rflx/parser/grammar.py
=> Issue 305: Improve performance of expression parsing

rflx/model.py, rflx/parser/grammar.py, rflx/parser/parser.py, tests/models.py, tests/test_model.py, tests/test_parser.py, tests/test_pyrflx.py, tests/test_verification.py
- Store enumeration elements as `Sequence[Tuple[StrID, Number]]` so we can check conflicts in `model.Model`
- Move conflict detection for enumeration literals into model
There are still a few checks in the parser which should be done in the model. We should open a different ticket for this, though.
=> Issue 298: Enums with identical literals not always detected

rflx/cli.py, tests/test_cli.py
Argparse has a specific [version action](https://docs.python.org/dev/library/argparse.html#action) to print the version. I think we should use it instead of implementing it by our own.
=> Use argparse version action

rflx/generator/common.py, rflx/model.py, tests/test_generator.py, tests/test_model.py
Besides fixing #328, this will remove useless code introduced while fixing #320 and remove a duplicate, incorrectly formatted error message.
Lessons learned:
- Always write unit tests
- Match the complete error message, not just the beginning
Close #328
=> Issue 328: Fix code generation and other issues

generated/rflx-ipv4-generic_packet.adb, rflx/generator/common.py, rflx/generator/core.py, test.gpr, tests/test_integration.py
=> Issue 329: Prevent name conflicts between literals and field names

.isort.cfg, rflx/model.py, tests/test_model.py, tests/test_verification.py, tests/utils.py
This fixes cases where negative fields length were not detected. The reason was a misconception of what we (need to) proof here. The attempted proof we had in the code so far was something like (`H1` and `H2` being the constraints from the range type):
```
H1: Length >= 40
H2: Length <= 1500
GOAL: Length - 50 >= 0
```
We then checked whether a solution could be found:
```Python
if proof.result != ProofResult.sat:
... # Error
```
What this does is checking whether **one** solution exists for the goal, which is clearly the case for `Length >= 50`. What we actually want and what is implemented now is proving that `Length - 50 < 0` is unsatisfiable.
Why wouldn't our tests detect this issue? The error message for a different check (that the start of the field is non-negative) was apparently …
=> Issue 336: Underflow not detected for range length field

rflx/parser/grammar.py, tests/test_parser.py
=> Issue 347: Allow array with imported element type

generated/rflx-arrays-generic_inner_message.adb, generated/rflx-arrays-generic_inner_message.ads, generated/rflx-arrays-generic_message.adb, generated/rflx-arrays-generic_message.ads, generated/rflx-arrays-generic_messages_message.adb, generated/rflx-arrays-generic_messages_message.ads, generated/rflx-ipv4-generic_option.adb, generated/rflx-ipv4-generic_option.ads, generated/rflx-ipv4-generic_packet.adb, generated/rflx-ipv4-generic_packet.ads, generated/rflx-ipv4.ads, generated/rflx-tlv-generic_message.adb, generated/rflx-tlv-generic_message.ads, generated/rflx-udp-generic_datagram.adb, generated/rflx-udp-generic_datagram.ads, rflx/generator/core.py, rflx/generator/generator.py, rflx/model.py, specs/ipv4.rflx, test.gpr, tests/rflx-in_ethernet-tests.adb, tests/rflx-in_ipv4-tests.adb, tests/rflx-ipv4-tests.adb, tests/test_pyrflx.py
=> Issue 353: Allow setting empty sequence field

rflx/pyrflx/typevalue.py, tests/test_pyrflx.py
=> Issue 346: Fix handling of prefixed literals in PyRFLX

rflx/expression.py, rflx/generator/common.py, rflx/generator/core.py, rflx/model.py, rflx/parser/ast.py, rflx/parser/grammar.py, rflx/parser/parser.py, rflx/pyrflx/typevalue.py, tests/test_expression.py, tests/test_model.py, tests/test_parser.py, tests/test_pyrflx.py, tests/tlv_with_checksum.rflx, tests/utils.py
=> Issue 222: Checksum specification

tests/property/test_generator.py
The verification tests led to timeouts in the nightly tests, as they take more than six hours.
https://github.com/Componolit/RecordFlux/runs/951950096?check_suite_focus=true
=> Reduce number of verification tests to prevent timeout in CI

rflx/graph.py, tests/test_graph.py
Prevent graph labels from overlapping by setting them as an additional intermediate node. We had to abandon the orthogonal layout in favor of a spline-based one, as otherwise the pseudo-labels would be visually disconnected.
=> Improve layout of graph labels

rflx/model.py, tests/test_model.py
=> Issue 410: Only merge satifiable final conditions

rflx/cli.py, tests/test_cli.py
Instead of checking if a subcommand was set manually it is possible to make a subcommand required.
=> Make subcommand required instead of manually checking

generated/rflx-icmp-generic_message.adb, generated/rflx-icmp-generic_message.ads, generated/rflx-icmp-message.ads, generated/rflx-icmp.ads, generated/rflx-in_ipv4-contains.ads, generated/rflx-in_ipv4-generic_contains.adb, generated/rflx-in_ipv4-generic_contains.ads, rflx/model/message.py, specs/in_ipv4.rflx, test.gpr, tests/test_model.py
- Add method to get paths from `AbstractMessage`
- Add ICMP to IPv4 refinements
- Correctly handle special `Message` variable
- Fix string representation of messages
=> RecordFuzz-specific adaptions

examples/apps/ping/ping.py, examples/apps/ping/specs/icmp.rflx, rflx/pyrflx/package.py, rflx/pyrflx/pyrflx.py, rflx/pyrflx/typevalue.py, tests/data/fixtures/pyrflx.py, tests/data/specs/refinement_with_checksum.rflx, tests/unit/pyrflx_test.py
The ping example has been broken for quite a while. The current version uses an ICMP spec without a checksum aspect. Originally the checksum has been calculated after setting all fields (including the checksum field itself) and then replaced the original checksum. With the current version of PyRFLX setting a field while skipping verification leads to all following fields being invalidated. To generate a valid message these fields have to be set again with the same values.
=> Fix ping example

rflx/error.py, rflx/identifier.py, tests/unit/expression_test.py, tests/unit/generator_test.py, tests/unit/identifier_test.py
=> Issue 529: Use custom errors instead of assertions for id check

rflx/error.py, rflx/pyrflx/__init__.py, rflx/pyrflx/bitstring.py, rflx/pyrflx/error.py, rflx/pyrflx/typevalue.py, tests/integration/pyrflx_test.py, tests/integration/specs_test.py, tests/unit/pyrflx_test.py
=> Issue 510: Use dedicated exception types for set and parse errors

.github/workflows/tests.yml, .pylintrc, README.md, rflx/ada.py, rflx/expression.py, rflx/model/message.py, setup.py, tests/unit/expression_test.py
This will also disable the code duplication detection of pylint because of a bug in the new pylint version. I don't think it is a big loss. We can re-enable it at some time.
Closes #581
=> Issue 581: Adapt to pylint 2.7.0 and add Python 3.9 to tests workflow

rflx/specification/parser.py, tests/data/specs/in_p1.rflx, tests/data/specs/p1.rflx, tests/data/specs/p2.rflx, tests/data/specs/p3.rflx, tests/data/specs/p4.rflx, tests/data/specs/subdir/message_type.rflx, tests/integration/specification_model_test.py, tests/unit/specification/parser_test.py
=> Issue 572, 589: Fix dependency resolution

examples/apps/ping/src/icmpv4.adb
=> Issue 494: Suppress warnings about set but not used arguments in example apps

rflx/pyrflx/typevalue.py, tests/data/fixtures/pyrflx.py, tests/data/specs/always_valid_aspect.rflx, tests/unit/pyrflx_test.py
This PR adds support for the `Always Valid` aspect in PyRFLX.
Closes #624
=> Issue 624: Support `Always Valid` aspect

ide/gnatstudio/recordflux.py
For some reason I always get a `KeyError` in `get_message_name` when displaying a message graph with the current version of the plugin. The fix is simple, but it is not clear to me why the behavior changed. I have tested the plugin with GNAT Studio 21.1 and a recent wavefront as older versions are not supported anymore (#602), but IIRC I didn't see the issue with these versions before.
=> Fix GNAT Studio plugin

rflx/pyrflx/typevalue.py, tests/data/fixtures/pyrflx.py, tests/data/specs/array_message.rflx, tests/data/specs/in_array_message.rflx, tests/integration/pyrflx_test.py, tests/unit/pyrflx_test.py
This PR should discuss the changes introduced to pyrflx to enable the coverage check for messages.
A boolean flag is added to the `_next_field` method. This is needed in order to determine when the covered link should be stored, as the `next_field` method is used during message initialization where the used link must not be stored.
In addition to this, a method is added to return all inner messages of a `MessageValue`. This is needed so that the coverage information of any nested messages can be obtained.
Closes #568
=> Issue 568: Coverage

rflx/pyrflx/typevalue.py, tests/unit/pyrflx_test.py
The solution required changes to the `set` method.
The value for the checksum field is set by using the `set` method and `preset_fields` is called inside `set`. There are 2 cases that need to be considered.
1 message generation: 
All fields are set manually and the checksum is calculated and **set automatically** if all fields that are needed for the checksum calculation have been set. `preset_fields` **must not be called inside** `set` when setting **the checksum value** after calculation. Calling `preset_fields` could lead to the message being invalid in case an Opaque field is located after the checksum field, as `preset_fields` clears the value of opaque fields if a predecessor field changes. This is required in case message fields are not set in the right order. In all other cases …
=> Issue 710: Fix recalculated checksum value set to field while parsing

rflx/cli.py, rflx/declaration.py, rflx/error.py, rflx/expression.py, rflx/identifier.py, rflx/model/message.py, rflx/model/model.py, rflx/model/session.py, rflx/model/type_.py, rflx/pyrflx/error.py, rflx/pyrflx/typevalue.py, rflx/specification/parser.py, rflx/statement.py, rflx/typing_.py, tests/data/specs/multiple_errors.rflx, tests/property/strategies.py, tests/unit/cli_test.py
A `--max-errors` switch now allows for limiting the number of errors printed before `rflx` exits. The `append` methods of the error class was removed and replaced by `extend` to avoid situations where RecordFlux exits due to an error before additional information was added to the error object (this still can happen when multiple `extend` calls are used, but it's less likely now).
~~Note that the global variable is not thread safe and thus unit tests changing the number of errors to report may influence other tests (resulting in truncated error messages and failed tests). Consequently, the new CLI test uses a large number of errors and a large `--max-errors` value (which exceed the maximum number of errors we test for in the other unit tests) such that other tests are not influenced.~~ …
=> Issue 748: Fail-fast mode

rflx/expression.py, rflx/model/message.py, tests/ide/ide_test.py, tests/unit/model/message_test.py
Ref. #625 
The proof time for the SPDM specification is down now from 15:26 min to 7:59 min by parallelizing all the verification steps that were easy to parallelize. I'd leave it at that for now, but not close #625 as we have some more idea to optimize the performance.
=> Issue 625: Optimize proof performance

rflx/ada.py, rflx/generator/session.py
The issue described in https://github.com/Componolit/RecordFlux/pull/754#issuecomment-906173181 will be fixed by the changes of this PR.
=> Fix generation of use clauses for sessions

rflx/specification/parser.py, tests/unit/specification/grammar_test.py
=> Issue 752: Fix generation for functions with builtin types

doc/Language-Reference.adoc, examples/apps/dhcp_client/specs/dhcp_client.rflx, rflx/model/session.py, setup.py, tests/integration/parameterized_messages/test.rflx, tests/integration/session_append_unconstrained/test.rflx, tests/integration/session_binding/test.rflx, tests/integration/session_channels/test.rflx, tests/integration/session_comprehension_on_message_field/test.rflx, tests/integration/session_comprehension_on_sequence/test.rflx, tests/integration/session_conversion/test.rflx, tests/integration/session_functions/test.rflx, tests/integration/session_minimal/test.rflx, tests/integration/session_reuse_of_message/test.rflx, tests/integration/session_sequence_append_head/test.rflx, tests/integration/session_simple/test.rflx, tests/integration/session_variable_initialization/test.rflx, tests/integration/specification_model_generator_test.py, tests/unit/model/session_test.py, tests/unit/specification/grammar_test.py, tests/unit/specification/parser_test.py
=> Issue 738: Rename `then` keyword to `goto` in state transitions

doc/Development.md
Alex and I had a discussion about our pull request process. We think that the current approach of referencing commits in review comments is not that useful and therefore not really worth the PR author's effort. I also added a part about how we are using squashing in pull requests.
=> Change description of pull request process

rflx/cli.py, rflx/integration.py, rflx/specification/parser.py, tests/unit/integration_test.py, tests/unit/specification/parser_test.py
- command line option for rfi files
- new argument of Parser and Integration for rfi files location
- move all rfi file handling to Integration class
- move testing accordingly
- new test for different location of rfi file
For #713
=> Issue 713: Add commandline option for location of rfi files

rflx/generator/allocator.py, tests/integration/session_comprehension_on_sequence/generated/rflx-test-session.adb, tests/integration/session_comprehension_on_sequence/generated/rflx-test-session_allocator.adb, tests/integration/session_comprehension_on_sequence/generated/rflx-test-session_allocator.ads, tests/integration/session_comprehension_on_sequence/test.rfi, tests/integration/session_sequence_append_head/generated/rflx-test-session.ads, tests/integration/session_sequence_append_head/generated/rflx-test-session_allocator.adb, tests/integration/session_sequence_append_head/generated/rflx-test-session_allocator.ads, tests/integration/session_sequence_append_head/test.rfi
For comprehensions and sequence head assignments, we derive the
buffer size from the requested buffer size for the target of the
assignment.
Also, we add rfi files to two tests to exercise this behavior.
For #713
=> Issue 713: Derive buffer sizes for some constructs

rflx/templates/rflx_generic_types.adb, tests/integration/messages/generated/rflx-rflx_generic_types.adb, tests/integration/messages_with_implict_size/generated/rflx-rflx_generic_types.adb, tests/integration/parameterized_messages/generated/rflx-rflx_generic_types.adb, tests/integration/session_append_unconstrained/generated/rflx-rflx_generic_types.adb, tests/integration/session_binding/generated/rflx-rflx_generic_types.adb, tests/integration/session_channel_multiplexing/generated/rflx-rflx_generic_types.adb, tests/integration/session_channels/generated/rflx-rflx_generic_types.adb, tests/integration/session_comprehension_on_message_field/generated/rflx-rflx_generic_types.adb, tests/integration/session_comprehension_on_sequence/generated/rflx-rflx_generic_types.adb, tests/integration/session_conversion/generated/rflx-rflx_generic_types.adb, tests/integration/session_endianness/generated/rflx-rflx_generic_types.adb, tests/integration/session_functions/generated/rflx-rflx_generic_types.adb, tests/integration/session_integration/generated/rflx-rflx_generic_types.adb, tests/integration/session_integration_multiple/generated/rflx-rflx_generic_types.adb, tests/integration/session_minimal/generated/rflx-rflx_generic_types.adb, tests/integration/session_reuse_of_message/generated/rflx-rflx_generic_types.adb, tests/integration/session_sequence_append_head/generated/rflx-rflx_generic_types.adb, tests/integration/session_simple/generated/rflx-rflx_generic_types.adb, tests/integration/session_variable_initialization/generated/rflx-rflx_generic_types.adb, tests/spark/generated/rflx-rflx_generic_types.adb
- Remove unneeded Bits variable.
- This should prove with both SPARK Pro 23.0w and SPARK Community
2021.
=> Simplify proof of Insert function

tests/utils.py
This subprogram may or may not be inlined depending on the wavefront
date. It's better to add a contract so that it gets proved in both
cases.
For #955
=> Add precondition to inlined subp

.github/workflows/tests.yml
The skipping of duplicate workflow runs also leads to the skipping of jobs based on file changes. A skipped job seems to be considered as a successful workflow run, so that the actual test is never executed (at least in some cases). I would propose to remove the detection of duplicate workflow runs and also remove the execution of tests on the `pull_request` trigger. Even with those changes, it is still not possible to run the `tests` workflow on external PR, so we do not really lose anything by reverting that commits (cf. #1017).
=> Revert changes to `tests` workflow

.vscode/launch.json, .vscode/settings.json, rflx/generator/session.py, rflx/model/__init__.py, rflx/model/message.py, rflx/model/model.py, rflx/model/package.py, rflx/model/session.py, rflx/model/type_.py, rflx/specification/parser.py, tests/unit/model/message_test.py, tests/unit/model/model_test.py
=> Use fully qualified type names

rflx/model/model.py, rflx/model/package.py, tests/unit/model/model_test.py
This PR fixes potential duplicate `with` imports by using a `set` to represent all imports in a package (instead of a `list`), and the output is stablized by sorting all the imports alphabetically.
=> Deduplicate the `with` imports being generated

CHANGELOG.md, doc/User-Guide.adoc, rflx/model/model.py, rflx/specification/style.py, tests/unit/model/model_test.py, tests/unit/specification/style_test.py
@rami3l @kanigsson We decided to limit the initial implementation to the deactivation of style checks for individual files. We will keep #1079 open to extend the implementation at a later stage. For the prototyping use case, `-- style: disable = all` can be added to the first line of the file. The specification generation was adapted, so that `-- style: disable = line-length` is added to the generated file, if necessary.
Ref. #1079
=> Issue 1079: Enable deactivation of style check for individual files

.github/workflows/tests.yml
This also improves the workflow to ensure that all tests are executed if the workflow was modified.
@kanigsson Proving the DHCP client still needs too much memory for using multiprocessing: https://github.com/Componolit/RecordFlux/runs/7090258097?check_suite_focus=true.
=> Fix failing DHCP Client test in CI

rflx/__init__.py, setup.py
With this change, a distinct version is determined based on the tags of the git repository. This approach has some limitations:
1.  The current version can be shown inside the repository using `python -m setuptools_scm`. If the project is installed in editable/development mode, the version shown by `rflx --version` might be incorrect. `rflx --version` shows the version of the last `pip install -e .`. A workaround could be executing `pip install --no-deps -e .` after creating a commit (e.g., as post-commit hook).
```console
$ python -m setuptools_scm
0.5.1.dev402+g479641262.d20220708
$ rflx --version          
RecordFlux 0.5.1.dev402+g479641262
[...]
$ pip install --no-deps -e .
[...]
$ rflx --version
RecordFlux 0.5.1.dev402+g479641262.d20220708
[...]
```
2. The git metadata is required …
=> Issue 1003: Determine package version based on SCM metadata

CHANGELOG.md, rflx/pyrflx/typevalue.py, tests/unit/pyrflx_test.py
=> Issue 1104: Fix missing type check for arguments of parameterized messages

.github/workflows/tests.yml, Makefile
This excludes all verification tests from the `test_python_coverage` target. This improves the time needed to determine the test coverage significantly (e.g., 1:30 min vs. 9:40 min on funafuti).
=> Improve time needed to determine test coverage

CHANGELOG.md, examples/apps/dhcp_client/dhcp_client.gpr, rflx/generator/session.py, tests/integration/messages_with_implict_size/generated/rflx-test-session.ads, tests/integration/messages_with_single_opaque_field/generated/rflx-test-session.ads, tests/integration/parameterized_messages/generated/rflx-test-session.ads, tests/integration/session_append_unconstrained/generated/rflx-test-session.ads, tests/integration/session_binding/generated/rflx-test-session.ads, tests/integration/session_case_expression_aggregate/generated/rflx-test-session.ads, tests/integration/session_case_expression_numeric/generated/rflx-test-session.ads, tests/integration/session_channel_multiplexing/generated/rflx-test-session.ads, tests/integration/session_channels/generated/rflx-test-session.ads, tests/integration/session_comprehension_head/generated/rflx-test-session.ads, tests/integration/session_comprehension_on_message_field/generated/rflx-test-session.ads, tests/integration/session_comprehension_on_sequence/generated/rflx-test-session.ads, tests/integration/session_conversion/generated/rflx-test-session.ads, tests/integration/session_endianness/generated/rflx-test-session.ads, tests/integration/session_functions/generated/rflx-test-session.ads, tests/integration/session_functions_opaque/generated/rflx-test-session.ads, tests/integration/session_integration/generated/rflx-test-session.ads, tests/integration/session_integration_multiple/generated/rflx-b-session.ads, tests/integration/session_integration_multiple/generated/rflx-test-session.ads, tests/integration/session_minimal/generated/rflx-test-session.ads, tests/integration/session_reuse_of_message/generated/rflx-test-session.ads, tests/integration/session_sequence_append/generated/rflx-test-session.ads, tests/integration/session_sequence_append_head/generated/rflx-test-session.ads, tests/integration/session_setting_of_message_fields/generated/rflx-test-session.ads, tests/integration/session_simple/generated/rflx-test-session.ads, tests/integration/session_variable_initialization/generated/rflx-test-session.ads
=> Issue 1155: Make In_IO_State function public

tests/tools/check_doc_test.py
This ensures that they are not run when compilation is disabled.
=> Mark tests which use "gprbuild" as "compliation"

Makefile, doc/development_guide/index.rst, doc/user_guide/index.rst, setup.py
I removed the `install_gnatstudio` (and it's bogus documentation) altogether as a properly installed `rflx` in a matching version is required for the plugin to work. Hence, it makes no sense to support installation from the source tree.
The installation should be fixed now. It happened to work when tested with `PYTHONPATH=. rflx setup_ide` in the source directory and we didn't test with the installed command. I added a respective test to the `test_installation` target.
Closes #1183 
Closes #1184
=> Issue 1183, 1183: Fix GNAT Studio plugin installation and documentation

.vscode/settings.json
Linting for Python worked for me only after I explicitly enabled it in the settings (cf. `"python.linting.enabled": true`).
I also changed the order of the settings. They are now ordered alphabetically.
=> Enable linting for Python in VS Code

.github/workflows/tests.yml, tests/integration/specification_model_generator_test.py, tools/generate_spark_test_code.py
=> Issue 993: Fix tests and generation of SPARK test code

CHANGELOG.md, rflx/model/message.py, tests/unit/model/message_test.py, tests/unit/specification/parser_test.py
=> Issue 874: Add detection of unused parameters

doc/language_reference/index.rst
=> Fix reference to `first`/`last` in `range_type`

tests/tools/check_doc_test.py, tools/check_doc.py
Fixes #1240
I decided to add an `api` subtype to Ada code blocks, as this seems to be the main unsupported use case in the manual.
With the `api` subtype, code is only syntax checked (`-gnats`), but style checks are also enforced (`gnaty` + `gnatwe`).
=> Add 'api' subtype for Ada code blocks

.github/workflows/deploy.yml, Makefile, doc/development_guide/index.rst, setup.py
Fixes #1162
It's not completely unlikely that this change will automatically deploy to PyPI next time we publish a release. Tested with a copy of RecordFlux on TestPyPI, but obviously not the real thing.
=> Deploy to PyPI using GitHub workflow

.github/workflows/tests.yml, Makefile
- Fix missing creation of cache directory before running GNATprove in property tests
- Remove unused make targets
- Ensure all tests are executed for "test" target
- Make target names more concise
- Fix phony targets
=> Ensure creation of cache directory before running GNATprove and refactor make targets

tests/property/expression_test.py, tests/property/specification_test.py
When running pylint with Python 3.9, it complained about an unsupported binary operation.
=> Prevent pylint errors
